# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(704, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.New = QtWidgets.QWidget()
        self.New.setObjectName("New")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.New)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.New)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.InputDate = QtWidgets.QDateTimeEdit(self.New)
        self.InputDate.setObjectName("InputDate")
        self.verticalLayout_5.addWidget(self.InputDate)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.line = QtWidgets.QFrame(self.New)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.New)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonNoWarring = QtWidgets.QRadioButton(self.New)
        self.radioButtonNoWarring.setObjectName("radioButtonNoWarring")
        self.horizontalLayout_2.addWidget(self.radioButtonNoWarring)
        self.radioButtonMiddle = QtWidgets.QRadioButton(self.New)
        self.radioButtonMiddle.setObjectName("radioButtonMiddle")
        self.horizontalLayout_2.addWidget(self.radioButtonMiddle)
        self.radioButtonWarring = QtWidgets.QRadioButton(self.New)
        self.radioButtonWarring.setObjectName("radioButtonWarring")
        self.horizontalLayout_2.addWidget(self.radioButtonWarring)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.New)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_6.addWidget(self.line_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.New)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RButtonOneTime = QtWidgets.QRadioButton(self.New)
        self.RButtonOneTime.setObjectName("RButtonOneTime")
        self.horizontalLayout.addWidget(self.RButtonOneTime)
        self.RButtinEveryDay = QtWidgets.QRadioButton(self.New)
        self.RButtinEveryDay.setObjectName("RButtinEveryDay")
        self.horizontalLayout.addWidget(self.RButtinEveryDay)
        self.RButtinEveryWeek = QtWidgets.QRadioButton(self.New)
        self.RButtinEveryWeek.setObjectName("RButtinEveryWeek")
        self.horizontalLayout.addWidget(self.RButtinEveryWeek)
        self.RButtinEveryMouth = QtWidgets.QRadioButton(self.New)
        self.RButtinEveryMouth.setObjectName("RButtinEveryMouth")
        self.horizontalLayout.addWidget(self.RButtinEveryMouth)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_3 = QtWidgets.QFrame(self.New)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.New)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_4.addWidget(self.label_5)
        self.LimitDate = QtWidgets.QDateEdit(self.New)
        self.LimitDate.setObjectName("LimitDate")
        self.verticalLayout_4.addWidget(self.LimitDate)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.line_4 = QtWidgets.QFrame(self.New)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_6.addWidget(self.line_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.New)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.NewText = QtWidgets.QPlainTextEdit(self.New)
        self.NewText.setObjectName("NewText")
        self.verticalLayout_7.addWidget(self.NewText)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.CreateButton = QtWidgets.QPushButton(self.New)
        self.CreateButton.setObjectName("CreateButton")
        self.verticalLayout_8.addWidget(self.CreateButton)
        self.tabWidget.addTab(self.New, "")
        self.View = QtWidgets.QWidget()
        self.View.setObjectName("View")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.View)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.View)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout.addWidget(self.calendarWidget)
        self.ViewButton = QtWidgets.QPushButton(self.View)
        self.ViewButton.setObjectName("ViewButton")
        self.verticalLayout.addWidget(self.ViewButton)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.listView = QtWidgets.QListView(self.View)
        self.listView.setObjectName("listView")
        self.horizontalLayout_4.addWidget(self.listView)
        self.tabWidget.addTab(self.View, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 704, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Load = QtWidgets.QAction(MainWindow)
        self.Load.setObjectName("Load")
        self.Save = QtWidgets.QAction(MainWindow)
        self.Save.setObjectName("Save")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.Load)
        self.menu.addAction(self.Save)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Выберите дату:"))
        self.label.setText(_translate("MainWindow", "Укажите важность:"))
        self.radioButtonNoWarring.setText(_translate("MainWindow", "Не важно"))
        self.radioButtonMiddle.setText(_translate("MainWindow", "Обычно"))
        self.radioButtonWarring.setText(_translate("MainWindow", "Важно"))
        self.label_4.setText(_translate("MainWindow", "Укажите периодичность:"))
        self.RButtonOneTime.setText(_translate("MainWindow", "Один раз"))
        self.RButtinEveryDay.setText(_translate("MainWindow", "Ежедневно"))
        self.RButtinEveryWeek.setText(_translate("MainWindow", "Еженедельно"))
        self.RButtinEveryMouth.setText(_translate("MainWindow", "Ежемесячно"))
        self.label_5.setText(_translate("MainWindow", "Граница повторений"))
        self.label_3.setText(_translate("MainWindow", "Опишите задачу"))
        self.CreateButton.setText(_translate("MainWindow", "Добавить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.New), _translate("MainWindow", "Добавить"))
        self.ViewButton.setText(_translate("MainWindow", "Показать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.View), _translate("MainWindow", "Просмотр"))
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.Load.setText(_translate("MainWindow", "Загрузить"))
        self.Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_3.setText(_translate("MainWindow", "Сохранить как"))
